export interface KeyRedefintion{
    name: string,
    values?: string[],
    b64?: boolean
}

export function isKeyRedefinition(k: any): k is KeyRedefintion{
    return typeof k === "object" && "name" in k && ("values" in k || "b64" in k);
}

export const gameKeys = {
    "GS_value": "stats",
    "GS_completed": "completedLevels",
    "GS_3": "userCoins",
    "GS_4": "bronzeUserCoins",
    "GS_5": "mapPackStars",
    "GS_6": "shopPurchases",
    "GS_7": "levelProgress",
    "GS_8": "[unused]",
    "GS_9": "levelStars",
    "GS_10": "officialLevelProgress",
    "GS_11": "dailyRewards",
    "GS_12": "quests",
    "GS_13": "[unused]",
    "GS_14": "questRewards",
    "GS_15": "queuedQuests",
    "GS_16": "dailyProgress",
    "GS_17": "dailyStars",
    "GS_18": "gauntletProgress",
    "GS_19": "treasureRoomRewards",
    "GS_20": "totalDemonKeys",
    "GS_21": "rewards",
    "GS_22": "gdWorldRewards",
    "GS_23": "gauntletProgress2",
    "GS_24": "dailyProgress2",
    "GS_25": "weeklyRewards",

    "GLM_01": "officialLevels",
    "GLM_02": "uploadedLevels",
    "GLM_03": "onlineLevels",
    "GLM_04": "starredLevels",
    "GLM_05": "[unused]",
    "GLM_06": "followedAccounts",
    "GLM_07": "recentlyPlayed",
    "GLM_08": "enabledSearchFilters",
    "GLM_09": "availableSearchFilters",
    "GLM_10": "timelyLevels",
    "GLM_11": "dailyID",
    "GLM_12": "likes",
    "GLM_13": "ratedLevels",
    "GLM_14": "reportedLevels",
    "GLM_15": "ratedDemons",
    "GLM_16": "gauntlets",
    "GLM_17": "weeklyID",
    "GLM_18": "levelFolders",
    "GLM_19": "createdLevelFolders",

    "GJA_001": "username",
    "GJA_002": "password",
    "GJA_003": "accountID",
    "GJA_004": "sessionID",

    "LLM_01": "localLevels",
    "LLM_02": "binaryVersion",

    "MDLM_001": "songInfo",
    "MDLM_002": "songPriority",

    "KBM_001": "keybinds",
    "KBM_002": "keybinds2",

    "texQuality": "textureQuality",
    "customObjectDict": "customObjects",
    "playerUserID": "playerID",
    "reportedAchievements": "achievements",
    "secretNumber": "cod3breakerSolution",
    "clickedGarage": "clickedIconKit",
    "hasRP": "isMod"
}

export const levelKeys = {
    "k1": "id",
    "k2": "name",
    "k3": { name: "description", b64: true } as KeyRedefintion,
    "k4": "levelData",
    "k5": "author",
    "k6": "playerID",
    "k7": { name: "difficulty", values: ["Easy", "Normal", "Hard", "Harder", "Insane", "Demon"] } as KeyRedefintion,
    "k8": "officialSongID",
    "k9": "ratingScore1",
    "k10": "ratingScore2",
    "k11": "downloads",
    "k12": "completions",
    "k13": "editable",
    "k14": "verified",
    "k15": "uploaded",
    "k16": "version",
    "k17": "gameVersion",
    "k18": "attempts",
    "k19": "percentage",
    "k20": "practicePercentage",
    "k21": { name: "levelType", values: ["official", "local", "saved", "online"] } as KeyRedefintion,
    "k22": "likes",
    "k23": { name: "length", values: ["Tiny", "Short", "Medium", "Long", "XL"] } as KeyRedefintion,
    "k24": "dislikes",
    "k25": "demon",
    "k26": "stars",
    "k27": "featuredPosition",
    "k33": "auto",
    "k34": "replayData",
    "k35": "playable",
    "k36": "jumps",
    "k37": "secretCoinsToUnlock",
    "k38": "levelUnlocked",
    "k41": "password",
    "k42": "copiedID",
    "k43": "twoPlayer",
    "k45": "customSongID",
    "k46": "revision",
    "k47": "edited",
    "k48": "objects",
    "k50": "binaryVersion",
    "k60": "accountID",
    "k61": "firstCoinCollected",
    "k62": "secondCoinCollected",
    "k63": "thirdCoinCollected",
    "k64": "totalCoins",
    "k65": "verifiedCoins",
    "k66": "requestedStars",
    "k67": "extraString",
    "k68": "antiCheatTriggered",
    "k69": "large",
    "k71": "manaOrbPercentage",
    "k72": "ldm",
    "k73": "ldmEnabled",
    "k74": "timelyID",
    "k75": "epic",
    "k76": "demonType",
    "k77": "isGauntlet",
    "k78": "isGauntlet2",
    "k79": "unlisted",
    "k80": "editorTime",
    "k81": "totalEditorTime",
    "k82": "favorited",
    "k83": "savedLevelIndex",
    "k84": "folder",
    "k85": "clicks",
    "k86": "bestAttemptTime",
    "k87": "seed",
    "k88": "scores",
    "k89": "leaderboardValid",
    "k90": "leaderboardPercentage",

    "kI1": "editorCameraX",
    "kI2": "editorCameraY",
    "kI3": "editorCameraZoom",
    "kI4": "editorBuildTabPage",
    "kI5": "editorBuildTabCategory",
    "kI6": "editorRecentPages",
    "kI7": "editorLayer"
}

export const difficultyList = {
    0: "NA",
    10: "Easy",
    20: "Normal",
    30: "Hard",
    40: "Harder",
    50: "Insane"
}

export const statKeys = {
    1: "jumps",
    2: "attempts",
    3: "officialLevelsCompleted",
    4: "onlineLevelsCompleted",
    5: "demons",
    6: "stars",
    7: "mapPacks",
    8: "coins",
    9: "destroyedPlayers",
    10: "likedLevels",
    11: "ratedLevels",
    12: "userCoins",
    13: "diamonds",
    14: "orbs",
    15: "completedDailies",
    16: "fireShards",
    17: "iceShards",
    18: "poisonShards",
    19: "shadowShards",
    20: "lavaShards",
    21: "demonKeys",
    22: "totalOrbs"
}